import styled from "@emotion/styled";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Link href="/day-1">Day 1</Link>
      </Container>
    </div>
  );
};

const Container = styled.main`
  padding: 12px;
`;

export default Home;
